### ISSUE TITLE
FFmpegプラグインを作り直す

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#453]
## 概要
#411 が適用されるとプラグインがもっと作りやすくなるので、今まで放置していた #357 を処理するためにBEditor.Extensions.FFmpegを作り直す

## メモ
- [x] #411 の入出力プラグインを実装
- [ ] BEditor.Extensions.FFmpeg内のEncoding, Decoderを削除
- [ ] 環境変数からffmpegのディレクトリを指定できるようにする

**Comment by yuto-trd** [comment]
https://github.com/b-editor/BEditor/blob/issue/%23453-rebuild-ffmpeg-ext/src/extensions/BEditor.Extensions.FFmpeg/Decoding/FFmpegReader.cs

音声のデコードに問題あり
