### ISSUE TITLE
Fontを読み込むときNullReferenceExceptionが発生する

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#468]
## 概要
以下の部分でNullReferenceExceptionが発生することがある。

https://github.com/b-editor/BEditor/blob/main/src/libraries/BEditor.Drawing/Font.cs#L44-L44

**Comment by nyanrus** [comment]
フォントの拡張子だけで判断して、フォントが実際に有効か確認してないゆえに、このバグが発生していると見受けられます。

### かんたんなバグの再現方法

1. とあるフォルダにテキストファイルを作成し、拡張子をttfに変える。
2. BEditorを起動し、設定->フォントで、そのフォルダを追加する。
3. BEditorを再起動する。
4. バグが再現される。

### かんたんなバグの解決方法
BEditor/src/libraries/BEditor.Drawing/Font.csのGetTypeface()での結果がnullか確認する。
