### ISSUE TITLE
Note from `FluentIcons` developer

### ISSUE THREAD

**Issue by davidxuang** [b-editor/beutl#563]
Hi, I’ve just updated the `FluentIcons` library, and a new package `FluentIcons.FluentAvalonia` is added, where `SymbolIcon` is derived from `FluentAvalonia.UI.Controls.FontIcon` instead of `Avalonia.Controls.Primitives.IconElement`. This should make it compatible with some `FluentAvalonia` v2 controls (e.g. `NavigationViewItem`). Please let me know if you experience bugs with it.

Please note that for now, only `preview` versions works for `FluentAvalonia` v2.

**Comment by davidxuang** [comment]
Close as read. Re-open if experiencing bugs.

**Comment by davidxuang** [comment]
@indigo-san

Hi there,

The `FluentIcons.FluentAvalonia` package has been renamed to `FluentIcons.Avalonia.Fluent`. You may want to migrate to new version at your convenience.

Regards.

**Comment by yuto-trd** [comment]
Thank you for letting me know.
I understand.
