### ISSUE TITLE
グループ制御の実装

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#629]
下位の要素に一括でエフェクトをかけたりする機能です。

~~実装としてはSceneRendererがグループ制御を評価するときに、
下位の要素を取得してグループ制御に渡す。
渡された要素は仮想的なRenderSceneで評価する。~~

**実際には以下のようになりました**
自分よりも下の要素を取得して、評価する。
返ってきた、Drawableを
複数の要素を入れられるDrawableに追加。
または、単一の要素を装飾するDrawableで包む (1)。

(1)の場合はもともとのZIndexが上書きされないようにする。

**Comment by yuto-trd** [comment]
#683
