### ISSUE TITLE
DeferredCanvasにDrawBackdropメソッドを追加

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#630]
DeferredCanvasに現在のフレームバッファを描画するDrawBackdropメソッドを追加する。

そのためのBackdropNodeを追加する。
```
DrawableNode
└ TransformNode
  └ FilterEffectNode
    └ ClearNode
    └ BackdropNode
```
この場合、DrawableNodeに入る前のフレームバッファを取得する。
そのため取得したフレームバッファにClearNodeを含まれない。

キャッシュは不可能にする。

**Comment by yuto-trd** [comment]
どの時点のフレームバッファを取得するのかを設定するために、`Snapshot`メソッドを作り、そこで返ってきた値を`DrawBackdrop`の引数にする。

```diff
public interface ICanvas
{
+    IBackdrop Snapshot();
+    void DrawBackdrop(IBackdrop backdrop);
}

+public interface IBackdrop
+{
+    void Draw(ImmediateCanvas canvas);
+}
```
