### ISSUE TITLE
イージング関数の設定ができない

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#632]
インライン表示から追加するときはイージング関数を設定できるが、
グラフエディタから既存のキーフレームのイージング関数を変更できない。

**Comment by yuto-trd** [comment]
~~コンテキストメニューから変更、追加する方法、とドラッグアンドドロップで変更、追加する方法をつくる。~~

~~ドラッグアンドドロップの場合、KeyModifierで追加か変更かを判別する。~~

~~コンテキストメニューの場合はイージング関数の選択をContentDialogで選べるようにする。~~

既にキーフレームがある場所でドロップされたら変更、ない場合は追加。
