### ISSUE TITLE
プレビュー再生時にUIが固まる

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#660]
ZorinOS 16.3でプレビュー再生時にUIが固まる

**Comment by yuto-trd** [comment]
OpenALを使って再生するとき、UIスレッドで処理しているので、全体をTask.Runで囲むかTask.Delayを挟む。

全体をTask.Runで囲む場合、whileの部分でCPU使用率が上がってしまう。

なので、音声バッファをQueueしたあと、音声バッファの長さの分、Task.Delayする。
