### ISSUE TITLE
スペースキーで再生/一時停止を切り替えられない

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#674]
スペースキーで再生/一時停止を切り替えられない

_Discordから_

**Comment by yuto-trd** [comment]
cc47aa9494b8f34c7631dc4158ec0d1fa5770a74
TextBoxがSpaceを処理済みとしてマークしないので、Play/Pauseを切り替えてしまう。

![KeyBindingSpace.gif](https://github.com/b-editor/beutl/assets/66758394/ab302c9a-aa21-440c-a09b-4343a4bc7803)

**Comment by yuto-trd** [comment]
赤線部をクリックすると編集ビューへのフォーカスが外れるので、キーボードのショートカットが効かない

![スクリーンショット 2023-08-28 001056](https://github.com/b-editor/beutl/assets/66758394/1180bb60-1906-4367-a120-c8aae333c6ff)
