### ISSUE TITLE
文字列などの参照型でアニメーションを有効にするとき、例外が発生する

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#679]
参照型でアニメーションを有効にすると`default(T)`が`null`になって`Animator.GetDefaultValue`で例外が発生する。

**解決方法**
`Animator.GetDefaultValue`で`null`を返すように変更して、`Animator.Interpolate`の引数を`nullable`にする。

また、アニメーションされる可能性のあるプロパティで`null`チェックをする。

**Comment by yuto-trd** [comment]
- #726
