### ISSUE TITLE
FilterEffectのTransformを使うと、描画キャッシュが透明になる

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#729]
通常のトランスフォームだけだとは問題ないが、FilterEffectのトランスフォームを併用すると以下のようになる。
描画キャッシュを無効化すると、問題は発生しない。

https://github.com/b-editor/beutl/assets/66758394/394f8fa7-f353-42f9-9e3b-fb6d6f657bd5

**Comment by yuto-trd** [comment]
~~`FilterEffectContext.Transform`で受け付けるMatrixを回転 (Skew)、スケールのみにする。~~
https://github.com/b-editor/beutl/blob/f6fcf2cced4e5334cfb181e45776414dceb2b9bd/src/Beutl.Engine/Graphics/FilterEffects/FilterEffectContext.cs#L202


~~移動分は`FEItem_Offset`にして、適用時に特殊処理する。~~
https://github.com/b-editor/beutl/blob/f6fcf2cced4e5334cfb181e45776414dceb2b9bd/src/Beutl.Engine/Graphics/FilterEffects/FilterEffectActivator.cs#L121

> [!IMPORTANT]
> 見当違いでした。原因はFilterEffectContext.TransformBounds内でのタイポ
> https://github.com/b-editor/beutl/commit/4a23b279cf1c935ab07fb7e9a4238c4e7f0b67e5#diff-e6f01bc0e6cc2d266a4f1d321772a786cfef48893a259680bc8edb42bfaf5940L485
