### ISSUE TITLE
型が見つからない場合の処理

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#765]
拡張機能の遅延読み込み (#752) により、必要な拡張機能が読み込まれる前に、
型が必要になる場合、型が見つからないためJsonからの復元に問題が発生する。

その場合、以下のようにダミーのオブジェクトを作成する。
https://github.com/b-editor/beutl/blob/e6b2b280db2c33fab921fb8cdced65d9d850c59a/src/Beutl.ProjectSystem/Operation/DummySourceOperator.cs#L8-L42

**拡張機能が読み込まれ型が解決できる場合**
- 自動的に復元できる場合は復元する。
- プロジェクトの再読み込みが必要な場合はユーザーに通知する。

**Comment by yuto-trd** [comment]
プロジェクトを開くとき拡張機能を読み込むのを待つという方法もある。
