### ISSUE TITLE
ライブラリのオーバーフロー表示

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#879]
今後、__[検索、イージング、ライブラリ、ノード]__ 以外にメニューを増やす可能性があるので、••• を表示させる。

![スクリーンショット 2023-08-22 140243~2.png](https://github.com/b-editor/beutl/assets/66758394/d51e0e27-2950-447b-b0fd-9c61c6ccb07b)

**Comment by yuto-trd** [comment]
難しそうなので追加、削除するメニューを表示させる
