### ISSUE TITLE
`nuget.config`のファイル名を大文字にする

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#931]
Linuxでは`nuget.config`が認識されず、新しく`NuGet.Config`が生成されてしまう。

https://github.com/b-editor/beutl/blob/be3e3e708024ef579dd1c1fe7f8f723242accfdd/src/Beutl.Api/Services/PackageInstaller.cs#L60

**Comment by yuto-trd** [comment]
`NuGet.Configuration.Settings`でファイル名を指定するようにした。
dd849be98913972345db723186749a1a738660e1
