### ISSUE TITLE
クリッピングの変更

### ISSUE THREAD

**Issue by indigo-san** [b-editor/beutl#946]
**自動調節機能**
アルファチャンネルが1以上の領域まで切り取る

**中心位置を変更するプロパティ**
今までは常に位置を固定していたが、それを解除できるようにする。

**プロパティの分割**
型をThicknessから個別のfloat型に変更する

**Comment by yuto-trd** [comment]
自動調節機能
描画まで境界線が確定しないので計測時にRect.Invalidを返す

以下は参考ソース
https://github.com/b-editor/beutl/blob/fc44a9efafe223f5e46de6fc966f45f15bb4e24d/src/libraries/BEditor.Primitive/Effects/PrimitiveImages/Clipping.cs#L180-L203
- **排他制御がない**ので、その対応が必要
- シングルスレッド, SIMD, マルチスレッドどれが速いかを計測する
